# Generated by Django 5.2.4 on 2025-08-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('CURRENTLY HANDLED', 'ON GOING'), ('COMPLETED', 'DONE'), ('NOT COMPLETED', 'NOT DONE')], max_length=100),
        ),
    ]
